# repo-root/ruff.toml

# Lint rules we want in general
select = ["E", "F"]
line-length  = 150

# File-specific ignores
[per-file-ignores]
"app/tests/*.py" = ["E731", "F401", "E501"]   # silence lambda-assign & unused-import in tests
