version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on: [ elasticsearch ]
    ports:
      - "5601:5601"

  rule_loader:
    build: ./ruleLoader
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./out:/app/out:ro
    environment:
      - ES_HOST=http://elasticsearch:9200
      - INDEX=test-index
    command: ["python", "uploadToES.py", "--replace-index"]


volumes:
  esdata:
